services:
  mod-scraper:
    build: .
    environment:
      - STEAM_USERNAME
      - STEAM_PASSWORD
      - STEAM_API_KEY
      - SKIP_UPDATE
      - MANUAL_DOWNLOAD
      - DOWNLOAD_SINCE
    volumes:
      - node_modules:/home/steam/app/node_modules
      - content:/home/steam/Steam/steamapps/workshop/content/

volumes:
  node_modules:
  content:
