name: Update database

on:
  schedule:
  - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build docker image
        run: docker build --progress=plain -t scrap-mechanic-mod-scraper .
        
      - name: Run the built image
        run: docker run --env STEAM_USERNAME --env STEAM_PASSWORD --env STEAM_API_KEY -t --name=smms scrap-mechanic-mod-scraper
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          
      - id: extract
        name: Extract the updated databases and changelog
        run: |
          docker cp smms:/home/steam/app/mod/Scripts/data/ ./mod/Scripts/
          docker cp smms:/home/steam/app/changelog.json ./changelog.json
          
          changelog=`cat ./changelog.json`
          echo "::set-output name=changelog::$changelog"

        
      - name: Commit updated databases
        if: ${{ fromJson(steps.extract.outputs.changelog).changeCount > 0 }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update databases" -m "${{ fromJson(steps.extract.outputs.changelog).messageMD }}"
          git push
