name: Update database

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build docker image
        run: docker build -t scrap-mechanic-mod-scraper .
        
      - name: Run the built image
        run: docker run -t scrap-mechanic-mod-scraper -e STEAM_USERNAME=${{ secrets.STEAM_USERNAME }} -e STEAM_PASSWORD=${{ secrets.STEAM_PASSWORD }} -e STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}
    
      # Debugging
      - run: ls -la /usr/app
        if: ${{ always() }}
