name: Update database

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    
    container: cm2network/steamcmd:root
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install node modules
        run: npm install --production
        
      - name: Run the script
        run: npm start
